spring:
  main:
    log-startup-info: true
    banner-mode: off

  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: dbsmol
    password: 12345
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        enable_lazy_load: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.zalando.logbook: DEBUG

jvm-args:
  -Djava.instrument.traceUsage
  -XX:+EnableDynamicAgentLoading